import type { LucideIcon } from "lucide-react";
import {
  User,
  Type,
  AlignLeft,
  MousePointerClick,
  Image as ImageIcon,
  Minus,
  MoveVertical,
  Share2,
  Video,
  Images,
  Code,
  FileCode,
  ClipboardList,
  ShoppingBag,
  CalendarClock,
  Timer,
  Map as MapIcon,
  HelpCircle,
  MessageSquareQuote,
  FileDown,
  Contact as ContactIcon,
  Rows,
  Rss,
  Sparkles,
  LayoutGrid,
  MessageCircle,
  Phone,
  Mail,
  MessageSquare,
  Send,
  UserPlus,
  QrCode,
} from "lucide-react";
import type { Block, BlockType, CustomCodeBlock } from "./types";
import { newId } from "./types";

export interface BlockDef {
  type: BlockType;
  label: string;
  description: string;
  icon: LucideIcon;
  group: "essentials" | "social" | "media" | "advanced" | "business" | "commerce" | "integrations";
  available: boolean;
  create: () => Block;
}

export const BLOCK_DEFS: BlockDef[] = [
  {
    type: "profile",
    label: "Profile",
    description: "Avatar, name and bio",
    icon: User,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "profile",
      displayName: "Your name",
      username: "",
      bio: "A short line about you.",
      location: "",
      shortDescription: "",
      verified: false,
    }),
  },
  {
    type: "heading",
    label: "Heading",
    description: "Section title",
    icon: Type,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "heading",
      text: "New heading",
      align: "center",
      fontSize: "xl",
      fontWeight: "bold",
    }),
  },
  {
    type: "text",
    label: "Text",
    description: "Paragraph text",
    icon: AlignLeft,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "text",
      text: "Write something…",
      kind: "paragraph",
      align: "left",
      fontSize: "sm",
      fontWeight: "normal",
    }),
  },
  {
    type: "button",
    label: "Button",
    description: "Link to anywhere",
    icon: MousePointerClick,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "button",
      label: "Visit link",
      url: "https://",
      action: "website",
      style: "filled",
      width: "full",
      align: "center",
      newTab: true,
      disabled: false,
    }),
  },
  {
    type: "buttonGroup",
    label: "Button group",
    description: "Multiple buttons",
    icon: Rows,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "buttonGroup",
      layout: "vertical",
      columns: 2,
      buttons: [
        { id: newId(), label: "Button 1", url: "https://", style: "filled" },
        { id: newId(), label: "Button 2", url: "https://", style: "outline" },
      ],
    }),
  },
  {
    type: "image",
    label: "Image",
    description: "Single image",
    icon: ImageIcon,
    group: "media",
    available: true,
    create: () => ({ id: newId(), type: "image", url: "", alt: "", rounded: "md", fit: "cover" }),
  },
  {
    type: "highlightCards",
    label: "Highlight cards",
    description: "Icon + title cards, any purpose",
    icon: LayoutGrid,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "highlightCards",
      title: "Highlights",
      layout: "grid",
      columns: 3,
      columnsTablet: 2,
      columnsMobile: 1,
      mobileScroll: true,
      gap: "md",
      cardStyle: "solid",
      align: "center",
      radius: 16,
      shadow: "md",
      iconSize: 34,
      border: true,
      animation: "fade-up",
      hover: "lift",
      cards: [
        { id: newId(), iconKind: "emoji", emoji: "⚡", title: "Fast", description: "Loads instantly" },
        { id: newId(), iconKind: "emoji", emoji: "🔒", title: "Secure", description: "Safe by default" },
        { id: newId(), iconKind: "emoji", emoji: "🎨", title: "Custom", description: "Make it yours" },
      ],
    }),
  },
  {
    type: "gallery",
    label: "Gallery",
    description: "Multiple images",
    icon: Images,
    group: "media",
    available: true,
    create: () => ({
      id: newId(),
      type: "gallery",
      layout: "grid",
      columns: 2,
      gap: "md",
      rounded: "md",
      images: [],
    }),
  },
  {
    type: "video",
    label: "Video",
    description: "YouTube, Vimeo, MP4",
    icon: Video,
    group: "media",
    available: true,
    create: () => ({
      id: newId(),
      type: "video",
      provider: "youtube",
      url: "",
      autoplay: false,
      loop: false,
      muted: true,
      rounded: "lg",
    }),
  },
  {
    type: "socialFeed",
    label: "Social feed",
    description: "Instagram & TikTok feeds",
    icon: Rss,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "socialFeed",
      provider: "instagram",
      handle: "",
      limit: 6,
    }),
  },
  {
    type: "divider",
    label: "Divider",
    description: "Visual separator",
    icon: Minus,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "divider",
      variant: "line",
      style: "solid",
      spacing: "md",
      thickness: "thin",
    }),
  },
  {
    type: "spacer",
    label: "Spacer",
    description: "Vertical space",
    icon: MoveVertical,
    group: "essentials",
    available: true,
    create: () => ({ id: newId(), type: "spacer", height: 24 }),
  },
  {
    type: "social",
    label: "Social icons",
    description: "Premium social icon row",
    icon: Share2,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "social",
      links: [],
      iconStyle: "glass",
      shape: "circle",
      iconSize: 18,
      spacing: 12,
      radius: 14,
      shadow: true,
      glow: false,
      colorMode: "brand",
      animation: "none",
      labels: "hidden",
      hoverEffect: "lift",
      align: "center",
    }),
  },
  {
    type: "testimonials",
    label: "Testimonials",
    description: "Customer reviews",
    icon: MessageSquareQuote,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "testimonials",
      title: "What people say",
      items: [
        {
          id: newId(),
          name: "Jane Doe",
          role: "Customer",
          rating: 5,
          review: "Absolutely fantastic!",
        },
      ],
    }),
  },
  {
    type: "faq",
    label: "FAQ",
    description: "Accordion questions",
    icon: HelpCircle,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "faq",
      title: "Frequently asked",
      items: [{ id: newId(), question: "How does it work?", answer: "Add your answer here." }],
    }),
  },
  {
    type: "countdown",
    label: "Countdown",
    description: "Target date timer",
    icon: Timer,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "countdown",
      title: "Launching soon",
      target: new Date(Date.now() + 7 * 24 * 3600 * 1000).toISOString(),
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      finishedLabel: "We're live!",
    }),
  },
  {
    type: "map",
    label: "Map",
    description: "Google Maps location",
    icon: MapIcon,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "map",
      mapUrl: "",
      locationName: "",
      address: "",
    }),
  },
  {
    type: "file",
    label: "File download",
    description: "PDF, DOCX, ZIP…",
    icon: FileDown,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "file",
      fileUrl: "",
      fileName: "document.pdf",
      fileKind: "pdf",
      buttonLabel: "Download PDF",
      pdfSourceType: "url",
    }),
  },
  {
    type: "contact",
    label: "Contact card",
    description: "Phone, email, address",
    icon: ContactIcon,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "contact",
      title: "Get in touch",
    }),
  },
  {
    type: "embed",
    label: "Embed",
    description: "Spotify, Loom, Figma…",
    icon: Sparkles,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "embed",
      provider: "spotify",
      url: "",
      height: 232,
    }),
  },
  {
    type: "customCode",
    label: "Custom Code",
    description: "HTML, CSS & embeds",
    icon: Code,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "customCode",
      title: "Custom Code",
      html: "",
      css: "",
      js: "",
      jsEnabled: false,
      containerWidth: "full",
      minHeight: 120,
      borderRadius: 0,
      lazy: true,
    }),
  },
  {
    type: "integration",
    label: "Integration",
    description: "Connected app block",
    icon: Code,
    group: "integrations",
    available: true,
    create: () => ({
      id: newId(),
      type: "integration",
      provider: "whatsapp",
      mode: "button",
      config: {},
    }),
  },
  {
    type: "socialButtons",
    label: "Social Buttons",
    description: "Labelled social link buttons",
    icon: Share2,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "socialButtons",
      layout: "stack",
      columns: 2,
      style: "filled",
      radius: 12,
      showIcons: true,
      colorMode: "brand",
      align: "center",
      items: [
        { id: newId(), platform: "instagram", label: "Instagram", url: "https://" },
        { id: newId(), platform: "youtube", label: "YouTube", url: "https://" },
      ],
    }),
  },
  {
    type: "whatsappButton",
    label: "WhatsApp Button",
    description: "One-tap WhatsApp chat",
    icon: MessageCircle,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "whatsappButton",
      value: "",
      label: "Chat on WhatsApp",
      message: "",
      style: "filled",
      size: "md",
      width: "full",
      align: "center",
      radius: 12,
      showIcon: true,
      brandColor: true,
    }),
  },
  {
    type: "callButton",
    label: "Call Button",
    description: "Tap to call your number",
    icon: Phone,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "callButton",
      value: "",
      label: "Call now",
      style: "filled",
      size: "md",
      width: "full",
      align: "center",
      radius: 12,
      showIcon: true,
      brandColor: true,
    }),
  },
  {
    type: "emailButton",
    label: "Email Button",
    description: "Open a prefilled email",
    icon: Mail,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "emailButton",
      value: "",
      label: "Send email",
      subject: "",
      message: "",
      style: "filled",
      size: "md",
      width: "full",
      align: "center",
      radius: 12,
      showIcon: true,
      brandColor: true,
    }),
  },
  {
    type: "smsButton",
    label: "SMS Button",
    description: "Send a text message",
    icon: MessageSquare,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "smsButton",
      value: "",
      label: "Send SMS",
      message: "",
      style: "filled",
      size: "md",
      width: "full",
      align: "center",
      radius: 12,
      showIcon: true,
      brandColor: true,
    }),
  },
  {
    type: "telegramButton",
    label: "Telegram Button",
    description: "Chat on Telegram",
    icon: Send,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "telegramButton",
      value: "",
      label: "Message on Telegram",
      message: "",
      style: "filled",
      size: "md",
      width: "full",
      align: "center",
      radius: 12,
      showIcon: true,
      brandColor: true,
    }),
  },
  {
    type: "followCard",
    label: "Follow Card",
    description: "Profile card with follow links",
    icon: UserPlus,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "followCard",
      name: "Your name",
      handle: "@yourhandle",
      description: "Follow me for more updates.",
      layout: "card",
      align: "center",
      radius: 16,
      showIcons: true,
      links: [
        { id: newId(), platform: "instagram", label: "Follow", url: "https://" },
      ],
    }),
  },
  {
    type: "qrContact",
    label: "QR Contact Card",
    description: "Scannable vCard QR code",
    icon: QrCode,
    group: "social",
    available: true,
    create: () => ({
      id: newId(),
      type: "qrContact",
      title: "Scan to save my contact",
      mode: "vcard",
      fullName: "Your name",
      org: "",
      phone: "",
      email: "",
      website: "",
      size: 180,
      color: "#111827",
      background: "#ffffff",
      showDetails: true,
      downloadable: true,
    }),
  },
  // ── Business Tools (lightweight, bio-link focused) ──────────────────
  {
    type: "form",
    label: "Contact Form",
    description: "Collect leads with custom fields",
    icon: ClipboardList,
    group: "business",
    available: true,
    create: () => ({
      id: newId(),
      type: "form",
      title: "Get in touch",
      description: "Fill the form and we'll get back to you shortly.",
      submitLabel: "Send message",
      successMessage: "Thanks! We've received your message.",
      errorMessage: "Something went wrong. Please try again.",
      cardStyle: "glass",
      radius: 18,
      columns: 1,
      shadow: "md",
      padding: 18,
      buttonStyle: "solid",
      buttonRadius: 10,
      preventDuplicates: true,
      fields: [
        { id: newId(), type: "name", label: "Name", placeholder: "Your name", required: true, width: "half" },
        { id: newId(), type: "email", label: "Email", placeholder: "you@example.com", required: true, width: "half" },
        { id: newId(), type: "phone", label: "Mobile number", placeholder: "+91 90000 00000", width: "half" },
        { id: newId(), type: "message", label: "Message", placeholder: "How can we help?", required: true, fullWidth: true, width: "full" },
      ],
    }),
  },
  {
    type: "store",
    label: "Mini Store",
    description: "Sell products & services",
    icon: ShoppingBag,
    group: "business",
    available: true,
    create: () => ({
      id: newId(),
      type: "store",
      title: "Shop & services",
      layout: "grid",
      columns: 2,
      cardStyle: "glass",
      radius: 18,
      showPrice: true,
      currency: "₹",
      items: [
        {
          id: newId(),
          kind: "digital",
          title: "Starter eBook",
          description: "Instant PDF download.",
          price: 499,
          oldPrice: 999,
          badge: "new",
          buttonLabel: "Download",
          downloadUrl: "",
        },
        {
          id: newId(),
          kind: "service",
          title: "Logo Design",
          description: "Custom logo with 3 concepts.",
          price: 4999,
          badge: "popular",
          buttonLabel: "Enquire on WhatsApp",
          whatsappNumber: "",
          whatsappMessage: "Hi! I'm interested in Logo Design.",
        },
      ],
    }),
  },
  {
    type: "booking",
    label: "Bookings Pro",
    description: "Appointment system",
    icon: CalendarClock,
    group: "business",
    available: true,
    create: () => ({
      id: newId(),
      type: "booking",
      title: "Book an Appointment",
      description: "Select a service below to schedule a time.",
      layout: "grid",
      columns: 2,
      services: [
        {
          id: newId(),
          kind: "appointment",
          title: "1:1 Strategy Call",
          subtitle: "30-minute deep dive",
          description: "A focused session to discuss your project and goals.",
          durationMin: 30,
          isFree: true,
          locationType: "online",
          meetingProvider: "google_meet",
        },
      ],
      availability: {
        workingDays: [1, 2, 3, 4, 5],
        workingHoursStart: "09:00",
        workingHoursEnd: "17:00",
        bookingIntervalMin: 30,
      },
      cardStyle: "glass",
      radius: 18,
    }),
  },
  // Reserved / later phases
  {
    type: "socialEmbed",
    label: "Social Media Embed",
    description: "Embed FB/IG posts & reels",
    icon: Share2,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "socialEmbed",
      platform: "auto",
      originalUrl: "",
      normalizedUrl: "",
      fullWidth: true,
      rounded: true,
    } as any),
  },
  // Reserved / later phases
  {
    type: "customCode",
    label: "HTML Builder",
    description: "Visual HTML & CSS",
    icon: FileCode,
    group: "advanced",
    available: true,
    create: () => ({ id: newId(), type: "customCode" } as CustomCodeBlock),
  },
];


// (Code icon now used by customCode block above)

export function getBlockDef(type: BlockType): BlockDef | undefined {
  return BLOCK_DEFS.find((d) => d.type === type);
}

export function blockLabel(block: Block): string {
  if (block.name) return block.name;
  const def = getBlockDef(block.type);
  return def?.label ?? block.type;
}

