import type { LucideIcon } from "lucide-react";
import {
  User,
  Type,
  AlignLeft,
  MousePointerClick,
  Image as ImageIcon,
  Minus,
  MoveVertical,
  Share2,
  Video,
  Images,
  Code,
  FileCode,
  ClipboardList,
  ShoppingBag,
  CalendarClock,
  Timer,
  Map as MapIcon,
  HelpCircle,
  MessageSquareQuote,
  FileDown,
  Contact as ContactIcon,
  Rows,
  Rss,
  Sparkles,
  LayoutGrid,
} from "lucide-react";
import type { Block, BlockType } from "./types";
import { newId } from "./types";

export interface BlockDef {
  type: BlockType;
  label: string;
  description: string;
  icon: LucideIcon;
  group: "essentials" | "media" | "advanced" | "commerce" | "integrations";
  available: boolean;
  create: () => Block;
}

export const BLOCK_DEFS: BlockDef[] = [
  {
    type: "profile",
    label: "Profile",
    description: "Avatar, name and bio",
    icon: User,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "profile",
      displayName: "Your name",
      username: "",
      bio: "A short line about you.",
      location: "",
      shortDescription: "",
      verified: false,
    }),
  },
  {
    type: "heading",
    label: "Heading",
    description: "Section title",
    icon: Type,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "heading",
      text: "New heading",
      align: "center",
      fontSize: "xl",
      fontWeight: "bold",
    }),
  },
  {
    type: "text",
    label: "Text",
    description: "Paragraph text",
    icon: AlignLeft,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "text",
      text: "Write something…",
      kind: "paragraph",
      align: "left",
      fontSize: "sm",
      fontWeight: "normal",
    }),
  },
  {
    type: "button",
    label: "Button",
    description: "Link to anywhere",
    icon: MousePointerClick,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "button",
      label: "Visit link",
      url: "https://",
      action: "website",
      style: "filled",
      width: "full",
      align: "center",
      newTab: true,
      disabled: false,
    }),
  },
  {
    type: "buttonGroup",
    label: "Button group",
    description: "Multiple buttons",
    icon: Rows,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "buttonGroup",
      layout: "vertical",
      columns: 2,
      buttons: [
        { id: newId(), label: "Button 1", url: "https://", style: "filled" },
        { id: newId(), label: "Button 2", url: "https://", style: "outline" },
      ],
    }),
  },
  {
    type: "image",
    label: "Image",
    description: "Single image",
    icon: ImageIcon,
    group: "media",
    available: true,
    create: () => ({ id: newId(), type: "image", url: "", alt: "", rounded: "md", fit: "cover" }),
  },
  {
    type: "highlightCards",
    label: "Highlight cards",
    description: "Icon + title cards, any purpose",
    icon: LayoutGrid,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "highlightCards",
      title: "Highlights",
      layout: "grid",
      columns: 3,
      columnsTablet: 2,
      columnsMobile: 1,
      mobileScroll: true,
      gap: "md",
      cardStyle: "solid",
      align: "center",
      radius: 16,
      shadow: "md",
      iconSize: 34,
      border: true,
      animation: "fade-up",
      hover: "lift",
      cards: [
        { id: newId(), iconKind: "emoji", emoji: "⚡", title: "Fast", description: "Loads instantly" },
        { id: newId(), iconKind: "emoji", emoji: "🔒", title: "Secure", description: "Safe by default" },
        { id: newId(), iconKind: "emoji", emoji: "🎨", title: "Custom", description: "Make it yours" },
      ],
    }),
  },
  {
    type: "gallery",
    label: "Gallery",
    description: "Multiple images",
    icon: Images,
    group: "media",
    available: true,
    create: () => ({
      id: newId(),
      type: "gallery",
      layout: "grid",
      columns: 2,
      gap: "md",
      rounded: "md",
      images: [],
    }),
  },
  {
    type: "video",
    label: "Video",
    description: "YouTube, Vimeo, MP4",
    icon: Video,
    group: "media",
    available: true,
    create: () => ({
      id: newId(),
      type: "video",
      provider: "youtube",
      url: "",
      autoplay: false,
      loop: false,
      muted: true,
      rounded: "lg",
    }),
  },
  {
    type: "socialFeed",
    label: "Social feed",
    description: "IG, YouTube, TikTok",
    icon: Rss,
    group: "media",
    available: true,
    create: () => ({
      id: newId(),
      type: "socialFeed",
      provider: "instagram",
      handle: "",
      limit: 6,
    }),
  },
  {
    type: "divider",
    label: "Divider",
    description: "Visual separator",
    icon: Minus,
    group: "essentials",
    available: true,
    create: () => ({
      id: newId(),
      type: "divider",
      variant: "line",
      style: "solid",
      spacing: "md",
      thickness: "thin",
    }),
  },
  {
    type: "spacer",
    label: "Spacer",
    description: "Vertical space",
    icon: MoveVertical,
    group: "essentials",
    available: true,
    create: () => ({ id: newId(), type: "spacer", height: 24 }),
  },
  {
    type: "social",
    label: "Social icons",
    description: "Row of social links",
    icon: Share2,
    group: "essentials",
    available: true,
    create: () => ({ id: newId(), type: "social", links: [] }),
  },
  {
    type: "testimonials",
    label: "Testimonials",
    description: "Customer reviews",
    icon: MessageSquareQuote,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "testimonials",
      title: "What people say",
      items: [
        {
          id: newId(),
          name: "Jane Doe",
          role: "Customer",
          rating: 5,
          review: "Absolutely fantastic!",
        },
      ],
    }),
  },
  {
    type: "faq",
    label: "FAQ",
    description: "Accordion questions",
    icon: HelpCircle,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "faq",
      title: "Frequently asked",
      items: [{ id: newId(), question: "How does it work?", answer: "Add your answer here." }],
    }),
  },
  {
    type: "countdown",
    label: "Countdown",
    description: "Target date timer",
    icon: Timer,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "countdown",
      title: "Launching soon",
      target: new Date(Date.now() + 7 * 24 * 3600 * 1000).toISOString(),
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      finishedLabel: "We're live!",
    }),
  },
  {
    type: "map",
    label: "Map",
    description: "Google Maps location",
    icon: MapIcon,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "map",
      mapUrl: "",
      locationName: "",
      address: "",
    }),
  },
  {
    type: "file",
    label: "File download",
    description: "PDF, DOCX, ZIP…",
    icon: FileDown,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "file",
      fileUrl: "",
      fileName: "document.pdf",
      fileKind: "pdf",
      buttonLabel: "Download",
    }),
  },
  {
    type: "contact",
    label: "Contact card",
    description: "Phone, email, address",
    icon: ContactIcon,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "contact",
      title: "Get in touch",
    }),
  },
  {
    type: "embed",
    label: "Embed",
    description: "Spotify, Loom, Figma…",
    icon: Sparkles,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "embed",
      provider: "spotify",
      url: "",
      height: 232,
    }),
  },
  {
    type: "customCode",
    label: "Custom Code",
    description: "HTML, CSS & embeds",
    icon: Code,
    group: "advanced",
    available: true,
    create: () => ({
      id: newId(),
      type: "customCode",
      title: "Custom Code",
      html: "",
      css: "",
      js: "",
      jsEnabled: false,
      containerWidth: "full",
      minHeight: 120,
      borderRadius: 0,
      lazy: true,
    }),
  },
  {
    type: "integration",
    label: "Integration",
    description: "Connected app block",
    icon: Code,
    group: "integrations",
    available: true,
    create: () => ({
      id: newId(),
      type: "integration",
      provider: "whatsapp",
      mode: "button",
      config: {},
    }),
  },
  // Reserved / later phases

  {
    type: "html",
    label: "HTML",
    description: "Coming soon",
    icon: FileCode,
    group: "advanced",
    available: false,
    create: () => ({ id: newId(), type: "html" }),
  },
  {
    type: "form",
    label: "Form",
    description: "Coming soon",
    icon: ClipboardList,
    group: "advanced",
    available: false,
    create: () => ({ id: newId(), type: "form" }),
  },
  {
    type: "store",
    label: "Store",
    description: "Coming soon",
    icon: ShoppingBag,
    group: "commerce",
    available: false,
    create: () => ({ id: newId(), type: "store" }),
  },
  {
    type: "booking",
    label: "Booking",
    description: "Coming soon",
    icon: CalendarClock,
    group: "commerce",
    available: false,
    create: () => ({ id: newId(), type: "booking" }),
  },
];

// (Code icon now used by customCode block above)

export function getBlockDef(type: BlockType): BlockDef | undefined {
  return BLOCK_DEFS.find((d) => d.type === type);
}

export function blockLabel(block: Block): string {
  if (block.name) return block.name;
  const def = getBlockDef(block.type);
  return def?.label ?? block.type;
}
