import {
  ArrowRight,
  ArrowUpRight,
  Check,
  ChevronRight,
  Play,
  Download,
  ShoppingCart,
  Heart,
  Star,
  Sparkles,
  Zap,
  Send,
  Mail,
  Phone,
  MessageCircle,
  MessageSquare,
  Calendar,
  Clock,
  MapPin,
  Globe,
  Link as LinkIcon,
  ExternalLink,
  Share2,
  Bookmark,
  Bell,
  Gift,
  Rocket,
  Flame,
  ThumbsUp,
  User,
  Users,
  Instagram,
  Youtube,
  Twitter,
  Facebook,
  Linkedin,
  Github,
  Music2,
  Camera,
  Video,
  Image as ImageIcon,
  FileText,
  Search,
  Settings,
  Lock,
  Unlock,
  CreditCard,
  DollarSign,
  Percent,
  Tag,
  Award,
  Trophy,
  Target,
  type LucideIcon,
} from "lucide-react";

/**
 * Icon library available to Button Group items.
 * Keys are stable — do not rename, they are persisted in bio_pages.content.
 */
export const ICON_LIBRARY: Record<string, LucideIcon> = {
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  chevronRight: ChevronRight,
  check: Check,
  play: Play,
  download: Download,
  cart: ShoppingCart,
  heart: Heart,
  star: Star,
  sparkles: Sparkles,
  zap: Zap,
  send: Send,
  mail: Mail,
  phone: Phone,
  chat: MessageCircle,
  message: MessageSquare,
  calendar: Calendar,
  clock: Clock,
  mapPin: MapPin,
  globe: Globe,
  link: LinkIcon,
  external: ExternalLink,
  share: Share2,
  bookmark: Bookmark,
  bell: Bell,
  gift: Gift,
  rocket: Rocket,
  flame: Flame,
  thumbsUp: ThumbsUp,
  user: User,
  users: Users,
  instagram: Instagram,
  youtube: Youtube,
  twitter: Twitter,
  facebook: Facebook,
  linkedin: Linkedin,
  github: Github,
  music: Music2,
  camera: Camera,
  video: Video,
  image: ImageIcon,
  file: FileText,
  search: Search,
  settings: Settings,
  lock: Lock,
  unlock: Unlock,
  card: CreditCard,
  dollar: DollarSign,
  percent: Percent,
  tag: Tag,
  award: Award,
  trophy: Trophy,
  target: Target,
};

export const ICON_KEYS = Object.keys(ICON_LIBRARY);

export function getIcon(key?: string): LucideIcon | null {
  if (!key) return null;
  return ICON_LIBRARY[key] ?? null;
}
