/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as SlugPageRouteImport } from './routes/$slug.$page'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai.generate'
import { Route as ApiAiChatRouteImport } from './routes/api/ai.chat'
import { Route as AuthenticatedBuilderIdRouteImport } from './routes/_authenticated.builder.$id'
import { Route as AuthenticatedAppTrackingRouteImport } from './routes/_authenticated.app.tracking'
import { Route as AuthenticatedAppTemplatesRouteImport } from './routes/_authenticated.app.templates'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated.app.settings'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated.app.projects'
import { Route as AuthenticatedAppMediaRouteImport } from './routes/_authenticated.app.media'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated.app.integrations'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated.app.help'
import { Route as AuthenticatedAppDomainsRouteImport } from './routes/_authenticated.app.domains'
import { Route as AuthenticatedAppConversionsRouteImport } from './routes/_authenticated.app.conversions'
import { Route as AuthenticatedAppCommunicationsRouteImport } from './routes/_authenticated.app.communications'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated.app.campaigns'
import { Route as AuthenticatedAppAutomationRouteImport } from './routes/_authenticated.app.automation'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated.app.analytics'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated.app.ai'
import { Route as AuthenticatedAppAiIndexRouteImport } from './routes/_authenticated.app.ai.index'
import { Route as AuthenticatedAppSettingsSessionsRouteImport } from './routes/_authenticated.app.settings.sessions'
import { Route as AuthenticatedAppSettingsSecurityRouteImport } from './routes/_authenticated.app.settings.security'
import { Route as AuthenticatedAppSettingsProfileRouteImport } from './routes/_authenticated.app.settings.profile'
import { Route as AuthenticatedAppSettingsPreferencesRouteImport } from './routes/_authenticated.app.settings.preferences'
import { Route as AuthenticatedAppSettingsPasswordRouteImport } from './routes/_authenticated.app.settings.password'
import { Route as AuthenticatedAppSettingsNotificationsRouteImport } from './routes/_authenticated.app.settings.notifications'
import { Route as AuthenticatedAppSettingsIdentityRouteImport } from './routes/_authenticated.app.settings.identity'
import { Route as AuthenticatedAppAiStudioRouteImport } from './routes/_authenticated.app.ai.studio'
import { Route as AuthenticatedAppAiDesignRouteImport } from './routes/_authenticated.app.ai.design'
import { Route as AuthenticatedAppAiConversationIdRouteImport } from './routes/_authenticated.app.ai.$conversationId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SlugPageRoute = SlugPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => SlugRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuilderIdRoute = AuthenticatedBuilderIdRouteImport.update({
  id: '/builder/$id',
  path: '/builder/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppTrackingRoute =
  AuthenticatedAppTrackingRouteImport.update({
    id: '/tracking',
    path: '/tracking',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTemplatesRoute =
  AuthenticatedAppTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMediaRoute = AuthenticatedAppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDomainsRoute = AuthenticatedAppDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConversionsRoute =
  AuthenticatedAppConversionsRouteImport.update({
    id: '/conversions',
    path: '/conversions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCommunicationsRoute =
  AuthenticatedAppCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomationRoute =
  AuthenticatedAppAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAiIndexRoute = AuthenticatedAppAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppAiRoute,
} as any)
const AuthenticatedAppSettingsSessionsRoute =
  AuthenticatedAppSettingsSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsSecurityRoute =
  AuthenticatedAppSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsProfileRoute =
  AuthenticatedAppSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsPreferencesRoute =
  AuthenticatedAppSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsPasswordRoute =
  AuthenticatedAppSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsNotificationsRoute =
  AuthenticatedAppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsIdentityRoute =
  AuthenticatedAppSettingsIdentityRouteImport.update({
    id: '/identity',
    path: '/identity',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppAiStudioRoute =
  AuthenticatedAppAiStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedAppAiRoute,
  } as any)
const AuthenticatedAppAiDesignRoute =
  AuthenticatedAppAiDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedAppAiRoute,
  } as any)
const AuthenticatedAppAiConversationIdRoute =
  AuthenticatedAppAiConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedAppAiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug/$page': typeof SlugPageRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/app/ai': typeof AuthenticatedAppAiRouteWithChildren
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/automation': typeof AuthenticatedAppAutomationRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/communications': typeof AuthenticatedAppCommunicationsRoute
  '/app/conversions': typeof AuthenticatedAppConversionsRoute
  '/app/domains': typeof AuthenticatedAppDomainsRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/media': typeof AuthenticatedAppMediaRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/tracking': typeof AuthenticatedAppTrackingRoute
  '/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/ai/$conversationId': typeof AuthenticatedAppAiConversationIdRoute
  '/app/ai/design': typeof AuthenticatedAppAiDesignRoute
  '/app/ai/studio': typeof AuthenticatedAppAiStudioRoute
  '/app/settings/identity': typeof AuthenticatedAppSettingsIdentityRoute
  '/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/app/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/app/settings/preferences': typeof AuthenticatedAppSettingsPreferencesRoute
  '/app/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/app/settings/security': typeof AuthenticatedAppSettingsSecurityRoute
  '/app/settings/sessions': typeof AuthenticatedAppSettingsSessionsRoute
  '/app/ai/': typeof AuthenticatedAppAiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug/$page': typeof SlugPageRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth': typeof AuthIndexRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/automation': typeof AuthenticatedAppAutomationRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/communications': typeof AuthenticatedAppCommunicationsRoute
  '/app/conversions': typeof AuthenticatedAppConversionsRoute
  '/app/domains': typeof AuthenticatedAppDomainsRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/media': typeof AuthenticatedAppMediaRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/tracking': typeof AuthenticatedAppTrackingRoute
  '/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/ai/$conversationId': typeof AuthenticatedAppAiConversationIdRoute
  '/app/ai/design': typeof AuthenticatedAppAiDesignRoute
  '/app/ai/studio': typeof AuthenticatedAppAiStudioRoute
  '/app/settings/identity': typeof AuthenticatedAppSettingsIdentityRoute
  '/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/app/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/app/settings/preferences': typeof AuthenticatedAppSettingsPreferencesRoute
  '/app/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/app/settings/security': typeof AuthenticatedAppSettingsSecurityRoute
  '/app/settings/sessions': typeof AuthenticatedAppSettingsSessionsRoute
  '/app/ai': typeof AuthenticatedAppAiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug/$page': typeof SlugPageRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRouteWithChildren
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/automation': typeof AuthenticatedAppAutomationRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/communications': typeof AuthenticatedAppCommunicationsRoute
  '/_authenticated/app/conversions': typeof AuthenticatedAppConversionsRoute
  '/_authenticated/app/domains': typeof AuthenticatedAppDomainsRoute
  '/_authenticated/app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/app/media': typeof AuthenticatedAppMediaRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/_authenticated/app/tracking': typeof AuthenticatedAppTrackingRoute
  '/_authenticated/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/ai/$conversationId': typeof AuthenticatedAppAiConversationIdRoute
  '/_authenticated/app/ai/design': typeof AuthenticatedAppAiDesignRoute
  '/_authenticated/app/ai/studio': typeof AuthenticatedAppAiStudioRoute
  '/_authenticated/app/settings/identity': typeof AuthenticatedAppSettingsIdentityRoute
  '/_authenticated/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/_authenticated/app/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/_authenticated/app/settings/preferences': typeof AuthenticatedAppSettingsPreferencesRoute
  '/_authenticated/app/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/_authenticated/app/settings/security': typeof AuthenticatedAppSettingsSecurityRoute
  '/_authenticated/app/settings/sessions': typeof AuthenticatedAppSettingsSessionsRoute
  '/_authenticated/app/ai/': typeof AuthenticatedAppAiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$slug/$page'
    | '/app'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/'
    | '/app/ai'
    | '/app/analytics'
    | '/app/automation'
    | '/app/campaigns'
    | '/app/communications'
    | '/app/conversions'
    | '/app/domains'
    | '/app/help'
    | '/app/integrations'
    | '/app/media'
    | '/app/projects'
    | '/app/settings'
    | '/app/templates'
    | '/app/tracking'
    | '/builder/$id'
    | '/api/ai/chat'
    | '/api/ai/generate'
    | '/api/public/track'
    | '/app/'
    | '/app/ai/$conversationId'
    | '/app/ai/design'
    | '/app/ai/studio'
    | '/app/settings/identity'
    | '/app/settings/notifications'
    | '/app/settings/password'
    | '/app/settings/preferences'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/sessions'
    | '/app/ai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$slug/$page'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth'
    | '/app/analytics'
    | '/app/automation'
    | '/app/campaigns'
    | '/app/communications'
    | '/app/conversions'
    | '/app/domains'
    | '/app/help'
    | '/app/integrations'
    | '/app/media'
    | '/app/projects'
    | '/app/settings'
    | '/app/templates'
    | '/app/tracking'
    | '/builder/$id'
    | '/api/ai/chat'
    | '/api/ai/generate'
    | '/api/public/track'
    | '/app'
    | '/app/ai/$conversationId'
    | '/app/ai/design'
    | '/app/ai/studio'
    | '/app/settings/identity'
    | '/app/settings/notifications'
    | '/app/settings/password'
    | '/app/settings/preferences'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/sessions'
    | '/app/ai'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$slug/$page'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/automation'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/communications'
    | '/_authenticated/app/conversions'
    | '/_authenticated/app/domains'
    | '/_authenticated/app/help'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/media'
    | '/_authenticated/app/projects'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/templates'
    | '/_authenticated/app/tracking'
    | '/_authenticated/builder/$id'
    | '/api/ai/chat'
    | '/api/ai/generate'
    | '/api/public/track'
    | '/_authenticated/app/'
    | '/_authenticated/app/ai/$conversationId'
    | '/_authenticated/app/ai/design'
    | '/_authenticated/app/ai/studio'
    | '/_authenticated/app/settings/identity'
    | '/_authenticated/app/settings/notifications'
    | '/_authenticated/app/settings/password'
    | '/_authenticated/app/settings/preferences'
    | '/_authenticated/app/settings/profile'
    | '/_authenticated/app/settings/security'
    | '/_authenticated/app/settings/sessions'
    | '/_authenticated/app/ai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/$slug/$page': {
      id: '/$slug/$page'
      path: '/$page'
      fullPath: '/$slug/$page'
      preLoaderRoute: typeof SlugPageRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/builder/$id': {
      id: '/_authenticated/builder/$id'
      path: '/builder/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof AuthenticatedBuilderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/tracking': {
      id: '/_authenticated/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AuthenticatedAppTrackingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/templates': {
      id: '/_authenticated/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AuthenticatedAppTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/media': {
      id: '/_authenticated/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AuthenticatedAppMediaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/help': {
      id: '/_authenticated/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/domains': {
      id: '/_authenticated/app/domains'
      path: '/domains'
      fullPath: '/app/domains'
      preLoaderRoute: typeof AuthenticatedAppDomainsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conversions': {
      id: '/_authenticated/app/conversions'
      path: '/conversions'
      fullPath: '/app/conversions'
      preLoaderRoute: typeof AuthenticatedAppConversionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/communications': {
      id: '/_authenticated/app/communications'
      path: '/communications'
      fullPath: '/app/communications'
      preLoaderRoute: typeof AuthenticatedAppCommunicationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automation': {
      id: '/_authenticated/app/automation'
      path: '/automation'
      fullPath: '/app/automation'
      preLoaderRoute: typeof AuthenticatedAppAutomationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai/': {
      id: '/_authenticated/app/ai/'
      path: '/'
      fullPath: '/app/ai/'
      preLoaderRoute: typeof AuthenticatedAppAiIndexRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
    '/_authenticated/app/settings/sessions': {
      id: '/_authenticated/app/settings/sessions'
      path: '/sessions'
      fullPath: '/app/settings/sessions'
      preLoaderRoute: typeof AuthenticatedAppSettingsSessionsRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/security': {
      id: '/_authenticated/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AuthenticatedAppSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/profile': {
      id: '/_authenticated/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AuthenticatedAppSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/preferences': {
      id: '/_authenticated/app/settings/preferences'
      path: '/preferences'
      fullPath: '/app/settings/preferences'
      preLoaderRoute: typeof AuthenticatedAppSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/password': {
      id: '/_authenticated/app/settings/password'
      path: '/password'
      fullPath: '/app/settings/password'
      preLoaderRoute: typeof AuthenticatedAppSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/notifications': {
      id: '/_authenticated/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AuthenticatedAppSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/identity': {
      id: '/_authenticated/app/settings/identity'
      path: '/identity'
      fullPath: '/app/settings/identity'
      preLoaderRoute: typeof AuthenticatedAppSettingsIdentityRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/ai/studio': {
      id: '/_authenticated/app/ai/studio'
      path: '/studio'
      fullPath: '/app/ai/studio'
      preLoaderRoute: typeof AuthenticatedAppAiStudioRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
    '/_authenticated/app/ai/design': {
      id: '/_authenticated/app/ai/design'
      path: '/design'
      fullPath: '/app/ai/design'
      preLoaderRoute: typeof AuthenticatedAppAiDesignRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
    '/_authenticated/app/ai/$conversationId': {
      id: '/_authenticated/app/ai/$conversationId'
      path: '/$conversationId'
      fullPath: '/app/ai/$conversationId'
      preLoaderRoute: typeof AuthenticatedAppAiConversationIdRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
  }
}

interface SlugRouteChildren {
  SlugPageRoute: typeof SlugPageRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugPageRoute: SlugPageRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AuthenticatedAppAiRouteChildren {
  AuthenticatedAppAiConversationIdRoute: typeof AuthenticatedAppAiConversationIdRoute
  AuthenticatedAppAiDesignRoute: typeof AuthenticatedAppAiDesignRoute
  AuthenticatedAppAiStudioRoute: typeof AuthenticatedAppAiStudioRoute
  AuthenticatedAppAiIndexRoute: typeof AuthenticatedAppAiIndexRoute
}

const AuthenticatedAppAiRouteChildren: AuthenticatedAppAiRouteChildren = {
  AuthenticatedAppAiConversationIdRoute: AuthenticatedAppAiConversationIdRoute,
  AuthenticatedAppAiDesignRoute: AuthenticatedAppAiDesignRoute,
  AuthenticatedAppAiStudioRoute: AuthenticatedAppAiStudioRoute,
  AuthenticatedAppAiIndexRoute: AuthenticatedAppAiIndexRoute,
}

const AuthenticatedAppAiRouteWithChildren =
  AuthenticatedAppAiRoute._addFileChildren(AuthenticatedAppAiRouteChildren)

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsIdentityRoute: typeof AuthenticatedAppSettingsIdentityRoute
  AuthenticatedAppSettingsNotificationsRoute: typeof AuthenticatedAppSettingsNotificationsRoute
  AuthenticatedAppSettingsPasswordRoute: typeof AuthenticatedAppSettingsPasswordRoute
  AuthenticatedAppSettingsPreferencesRoute: typeof AuthenticatedAppSettingsPreferencesRoute
  AuthenticatedAppSettingsProfileRoute: typeof AuthenticatedAppSettingsProfileRoute
  AuthenticatedAppSettingsSecurityRoute: typeof AuthenticatedAppSettingsSecurityRoute
  AuthenticatedAppSettingsSessionsRoute: typeof AuthenticatedAppSettingsSessionsRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsIdentityRoute:
      AuthenticatedAppSettingsIdentityRoute,
    AuthenticatedAppSettingsNotificationsRoute:
      AuthenticatedAppSettingsNotificationsRoute,
    AuthenticatedAppSettingsPasswordRoute:
      AuthenticatedAppSettingsPasswordRoute,
    AuthenticatedAppSettingsPreferencesRoute:
      AuthenticatedAppSettingsPreferencesRoute,
    AuthenticatedAppSettingsProfileRoute: AuthenticatedAppSettingsProfileRoute,
    AuthenticatedAppSettingsSecurityRoute:
      AuthenticatedAppSettingsSecurityRoute,
    AuthenticatedAppSettingsSessionsRoute:
      AuthenticatedAppSettingsSessionsRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRouteWithChildren
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppAutomationRoute: typeof AuthenticatedAppAutomationRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppCommunicationsRoute: typeof AuthenticatedAppCommunicationsRoute
  AuthenticatedAppConversionsRoute: typeof AuthenticatedAppConversionsRoute
  AuthenticatedAppDomainsRoute: typeof AuthenticatedAppDomainsRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppMediaRoute: typeof AuthenticatedAppMediaRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppTemplatesRoute: typeof AuthenticatedAppTemplatesRoute
  AuthenticatedAppTrackingRoute: typeof AuthenticatedAppTrackingRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAiRoute: AuthenticatedAppAiRouteWithChildren,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppAutomationRoute: AuthenticatedAppAutomationRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppCommunicationsRoute: AuthenticatedAppCommunicationsRoute,
  AuthenticatedAppConversionsRoute: AuthenticatedAppConversionsRoute,
  AuthenticatedAppDomainsRoute: AuthenticatedAppDomainsRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppMediaRoute: AuthenticatedAppMediaRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppTemplatesRoute: AuthenticatedAppTemplatesRoute,
  AuthenticatedAppTrackingRoute: AuthenticatedAppTrackingRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedBuilderIdRoute: typeof AuthenticatedBuilderIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedBuilderIdRoute: AuthenticatedBuilderIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
