/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppTemplatesRouteImport } from './routes/_authenticated.app.templates'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated.app.settings'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated.app.projects'
import { Route as AuthenticatedAppMediaRouteImport } from './routes/_authenticated.app.media'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated.app.integrations'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated.app.help'
import { Route as AuthenticatedAppDomainsRouteImport } from './routes/_authenticated.app.domains'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated.app.analytics'
import { Route as AuthenticatedAppSettingsSessionsRouteImport } from './routes/_authenticated.app.settings.sessions'
import { Route as AuthenticatedAppSettingsSecurityRouteImport } from './routes/_authenticated.app.settings.security'
import { Route as AuthenticatedAppSettingsProfileRouteImport } from './routes/_authenticated.app.settings.profile'
import { Route as AuthenticatedAppSettingsPreferencesRouteImport } from './routes/_authenticated.app.settings.preferences'
import { Route as AuthenticatedAppSettingsPasswordRouteImport } from './routes/_authenticated.app.settings.password'
import { Route as AuthenticatedAppSettingsNotificationsRouteImport } from './routes/_authenticated.app.settings.notifications'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTemplatesRoute =
  AuthenticatedAppTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMediaRoute = AuthenticatedAppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDomainsRoute = AuthenticatedAppDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsSessionsRoute =
  AuthenticatedAppSettingsSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsSecurityRoute =
  AuthenticatedAppSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsProfileRoute =
  AuthenticatedAppSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsPreferencesRoute =
  AuthenticatedAppSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsPasswordRoute =
  AuthenticatedAppSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsNotificationsRoute =
  AuthenticatedAppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/domains': typeof AuthenticatedAppDomainsRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/media': typeof AuthenticatedAppMediaRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/app/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/app/settings/preferences': typeof AuthenticatedAppSettingsPreferencesRoute
  '/app/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/app/settings/security': typeof AuthenticatedAppSettingsSecurityRoute
  '/app/settings/sessions': typeof AuthenticatedAppSettingsSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth': typeof AuthIndexRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/domains': typeof AuthenticatedAppDomainsRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/media': typeof AuthenticatedAppMediaRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/app/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/app/settings/preferences': typeof AuthenticatedAppSettingsPreferencesRoute
  '/app/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/app/settings/security': typeof AuthenticatedAppSettingsSecurityRoute
  '/app/settings/sessions': typeof AuthenticatedAppSettingsSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/domains': typeof AuthenticatedAppDomainsRoute
  '/_authenticated/app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/app/media': typeof AuthenticatedAppMediaRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/_authenticated/app/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/_authenticated/app/settings/preferences': typeof AuthenticatedAppSettingsPreferencesRoute
  '/_authenticated/app/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/_authenticated/app/settings/security': typeof AuthenticatedAppSettingsSecurityRoute
  '/_authenticated/app/settings/sessions': typeof AuthenticatedAppSettingsSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/'
    | '/app/analytics'
    | '/app/domains'
    | '/app/help'
    | '/app/integrations'
    | '/app/media'
    | '/app/projects'
    | '/app/settings'
    | '/app/templates'
    | '/app/'
    | '/app/settings/notifications'
    | '/app/settings/password'
    | '/app/settings/preferences'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth'
    | '/app/analytics'
    | '/app/domains'
    | '/app/help'
    | '/app/integrations'
    | '/app/media'
    | '/app/projects'
    | '/app/settings'
    | '/app/templates'
    | '/app'
    | '/app/settings/notifications'
    | '/app/settings/password'
    | '/app/settings/preferences'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/sessions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/domains'
    | '/_authenticated/app/help'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/media'
    | '/_authenticated/app/projects'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/templates'
    | '/_authenticated/app/'
    | '/_authenticated/app/settings/notifications'
    | '/_authenticated/app/settings/password'
    | '/_authenticated/app/settings/preferences'
    | '/_authenticated/app/settings/profile'
    | '/_authenticated/app/settings/security'
    | '/_authenticated/app/settings/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/templates': {
      id: '/_authenticated/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AuthenticatedAppTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/media': {
      id: '/_authenticated/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AuthenticatedAppMediaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/help': {
      id: '/_authenticated/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/domains': {
      id: '/_authenticated/app/domains'
      path: '/domains'
      fullPath: '/app/domains'
      preLoaderRoute: typeof AuthenticatedAppDomainsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/sessions': {
      id: '/_authenticated/app/settings/sessions'
      path: '/sessions'
      fullPath: '/app/settings/sessions'
      preLoaderRoute: typeof AuthenticatedAppSettingsSessionsRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/security': {
      id: '/_authenticated/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AuthenticatedAppSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/profile': {
      id: '/_authenticated/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AuthenticatedAppSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/preferences': {
      id: '/_authenticated/app/settings/preferences'
      path: '/preferences'
      fullPath: '/app/settings/preferences'
      preLoaderRoute: typeof AuthenticatedAppSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/password': {
      id: '/_authenticated/app/settings/password'
      path: '/password'
      fullPath: '/app/settings/password'
      preLoaderRoute: typeof AuthenticatedAppSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/notifications': {
      id: '/_authenticated/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AuthenticatedAppSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
  }
}

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsNotificationsRoute: typeof AuthenticatedAppSettingsNotificationsRoute
  AuthenticatedAppSettingsPasswordRoute: typeof AuthenticatedAppSettingsPasswordRoute
  AuthenticatedAppSettingsPreferencesRoute: typeof AuthenticatedAppSettingsPreferencesRoute
  AuthenticatedAppSettingsProfileRoute: typeof AuthenticatedAppSettingsProfileRoute
  AuthenticatedAppSettingsSecurityRoute: typeof AuthenticatedAppSettingsSecurityRoute
  AuthenticatedAppSettingsSessionsRoute: typeof AuthenticatedAppSettingsSessionsRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsNotificationsRoute:
      AuthenticatedAppSettingsNotificationsRoute,
    AuthenticatedAppSettingsPasswordRoute:
      AuthenticatedAppSettingsPasswordRoute,
    AuthenticatedAppSettingsPreferencesRoute:
      AuthenticatedAppSettingsPreferencesRoute,
    AuthenticatedAppSettingsProfileRoute: AuthenticatedAppSettingsProfileRoute,
    AuthenticatedAppSettingsSecurityRoute:
      AuthenticatedAppSettingsSecurityRoute,
    AuthenticatedAppSettingsSessionsRoute:
      AuthenticatedAppSettingsSessionsRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppDomainsRoute: typeof AuthenticatedAppDomainsRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppMediaRoute: typeof AuthenticatedAppMediaRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppTemplatesRoute: typeof AuthenticatedAppTemplatesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppDomainsRoute: AuthenticatedAppDomainsRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppMediaRoute: AuthenticatedAppMediaRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppTemplatesRoute: AuthenticatedAppTemplatesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
