/**
 * Free tier theme definitions (20 themes).
 * Each theme is a distinct combination of layout + tokens.
 */
import type { ThemeSpec } from "../build";

export const FREE_THEMES: ThemeSpec[] = [
  {
    id: "aurora-minimal",
    name: "Aurora Minimal",
    description: "Editorial, monochrome, calm.",
    category: "minimal",
    tier: "free",
    layoutId: "classic",
    preset: "minimal",
    style: "light",
    tags: ["clean", "editorial"],
    popularity: 92,
    flags: { isFeatured: true },
  },
  {
    id: "paper-notion",
    name: "Paper",
    description: "Notion-inspired page with airy serif type.",
    category: "writer",
    tier: "free",
    layoutId: "notion",
    preset: "minimal",
    style: "light",
    tags: ["notion", "docs", "serif"],
    popularity: 74,
    colors: { background: "#fbfaf7", backgroundSolid: "#fbfaf7", surface: "#f4f2ec", text: "#191818", textMuted: "#5a5854", border: "#e6e1d5" },
    typography: { fontFamily: '"Lora", Georgia, serif', headingFamily: '"Lora", Georgia, serif', headingWeight: 600, baseSize: 15 },
    googleFonts: ["Lora"],
  },
  {
    id: "clean-portfolio",
    name: "Clean Portfolio",
    description: "Minimal editorial portfolio grid.",
    category: "portfolio",
    tier: "free",
    layoutId: "portfolio",
    preset: "minimal",
    style: "light",
    tags: ["portfolio", "grid"],
    popularity: 68,
  },
  {
    id: "soft-pastel",
    name: "Soft Pastel",
    description: "Cotton-candy palette with rounded buttons.",
    category: "creator",
    tier: "free",
    layoutId: "classic",
    preset: "creator",
    style: "gradient",
    tags: ["pastel", "cute"],
    popularity: 63,
    colors: {
      background: "linear-gradient(180deg,#ffe4f1 0%,#e0e7ff 100%)",
      backgroundSolid: "#ffe4f1",
      primary: "#a855f7",
      accent: "#f472b6",
    },
  },
  {
    id: "mono-editorial",
    name: "Mono Editorial",
    description: "Black-and-white magazine layout.",
    category: "writer",
    tier: "free",
    layoutId: "editorial",
    preset: "minimal",
    style: "light",
    tags: ["editorial", "mono"],
    popularity: 55,
    typography: { fontFamily: '"Playfair Display", Georgia, serif', headingFamily: '"Playfair Display", Georgia, serif', headingWeight: 700 },
    googleFonts: ["Playfair Display"],
  },
  {
    id: "sunset-creator",
    name: "Sunset Creator",
    description: "Warm gradient background for creators.",
    category: "creator",
    tier: "free",
    layoutId: "classic",
    preset: "creator",
    style: "gradient",
    tags: ["warm", "gradient"],
    popularity: 78,
  },
  {
    id: "corporate-navy",
    name: "Corporate Navy",
    description: "Corporate, structured, trustworthy.",
    category: "business",
    tier: "free",
    layoutId: "corporate",
    preset: "business",
    style: "light",
    tags: ["corporate", "b2b"],
    popularity: 66,
  },
  {
    id: "keystone-realestate",
    name: "Keystone",
    description: "Trusted corporate look for realtors.",
    category: "realestate",
    tier: "free",
    layoutId: "corporate",
    preset: "business",
    style: "light",
    tags: ["listings"],
    popularity: 52,
  },
  {
    id: "campus-education",
    name: "Campus",
    description: "Trusted look for educators.",
    category: "education",
    tier: "free",
    layoutId: "classic",
    preset: "business",
    style: "light",
    tags: ["education"],
    popularity: 48,
  },
  {
    id: "cause-nonprofit",
    name: "Cause",
    description: "Clean minimal for nonprofits.",
    category: "nonprofit",
    tier: "free",
    layoutId: "classic",
    preset: "minimal",
    style: "light",
    tags: ["nonprofit"],
    popularity: 44,
  },
  {
    id: "shopfront-ecom",
    name: "Shopfront",
    description: "Bento grid layout for e-commerce.",
    category: "ecommerce",
    tier: "free",
    layoutId: "bento",
    preset: "business",
    style: "light",
    tags: ["shop"],
    popularity: 61,
  },
  {
    id: "mentor-coach",
    name: "Mentor",
    description: "Warm palette for coaches.",
    category: "coach",
    tier: "free",
    layoutId: "classic",
    preset: "creator",
    style: "gradient",
    tags: ["mentor"],
    popularity: 50,
  },
  {
    id: "waveform-podcaster",
    name: "Waveform",
    description: "Bold modern look for podcasters.",
    category: "podcaster",
    tier: "free",
    layoutId: "classic",
    preset: "modern",
    style: "light",
    tags: ["podcast"],
    popularity: 58,
  },
  {
    id: "spotlight-influencer",
    name: "Spotlight",
    description: "Story-card layout for influencers.",
    category: "influencer",
    tier: "free",
    layoutId: "story-card",
    preset: "creator",
    style: "gradient",
    tags: ["creator"],
    popularity: 71,
  },
  {
    id: "wander-travel",
    name: "Wander",
    description: "Warm gradient for travel creators.",
    category: "travel",
    tier: "free",
    layoutId: "classic",
    preset: "creator",
    style: "gradient",
    tags: ["travel"],
    popularity: 54,
  },
  {
    id: "mint-fresh",
    name: "Mint Fresh",
    description: "Cool mint accents on white.",
    category: "minimal",
    tier: "free",
    layoutId: "classic",
    preset: "minimal",
    style: "light",
    tags: ["mint", "fresh"],
    popularity: 47,
    colors: { primary: "#10b981", accent: "#059669", link: "#10b981" },
  },
  {
    id: "slate-professional",
    name: "Slate Pro",
    description: "Slate-and-white professional look.",
    category: "consultant",
    tier: "free",
    layoutId: "linear",
    preset: "business",
    style: "light",
    tags: ["consulting"],
    popularity: 49,
    colors: { primary: "#334155", accent: "#0f172a", background: "#f8fafc", backgroundSolid: "#f8fafc" },
  },
  {
    id: "rose-personal",
    name: "Rose",
    description: "Rose gradient for personal brands.",
    category: "personal",
    tier: "free",
    layoutId: "classic",
    preset: "creator",
    style: "gradient",
    tags: ["personal"],
    popularity: 60,
    colors: {
      background: "linear-gradient(180deg,#ffe4e6 0%,#fce7f3 100%)",
      backgroundSolid: "#ffe4e6",
      primary: "#e11d48",
      accent: "#f43f5e",
    },
  },
  {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    description: "Fresh aqua glass palette.",
    category: "travel",
    tier: "free",
    layoutId: "glass",
    preset: "glass",
    style: "glass",
    tags: ["ocean", "glass"],
    popularity: 65,
    colors: {
      background: "linear-gradient(135deg,#a7f3d0 0%,#7dd3fc 100%)",
      backgroundSolid: "#7dd3fc",
      primary: "#0e7490",
      accent: "#06b6d4",
    },
  },
  {
    id: "terminal-lite",
    name: "Terminal Lite",
    description: "Mono terminal aesthetic on paper.",
    category: "developer",
    tier: "free",
    layoutId: "terminal",
    preset: "minimal",
    style: "light",
    tags: ["dev", "mono"],
    popularity: 57,
    colors: { background: "#f4f4f5", backgroundSolid: "#f4f4f5", primary: "#18181b", accent: "#10b981" },
    typography: {
      fontFamily: '"JetBrains Mono", ui-monospace, monospace',
      headingFamily: '"JetBrains Mono", ui-monospace, monospace',
      buttonFamily: '"JetBrains Mono", ui-monospace, monospace',
    },
    googleFonts: ["JetBrains Mono"],
  },
];
