/**
 * Premium tier theme definitions (50 premium + 5 enterprise = 55 themes).
 * Each theme uses a unique layout + typography + button combination.
 */
import type { ThemeSpec } from "../build";

export const PREMIUM_THEMES: ThemeSpec[] = [
  // ── Design-system inspired ────────────────────────────────────────
  {
    id: "apple-hero",
    name: "Apple",
    description: "Huge headline, restrained buttons, cinematic space.",
    category: "modern",
    tier: "premium",
    layoutId: "apple",
    preset: "minimal",
    style: "light",
    tags: ["apple", "cinematic"],
    popularity: 96,
    flags: { isFeatured: true, isTrending: true },
    colors: { background: "#ffffff", backgroundSolid: "#ffffff", primary: "#000000", accent: "#0071e3", text: "#1d1d1f" },
    typography: {
      fontFamily: '"Sora", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      headingFamily: '"Sora", -apple-system, sans-serif',
      headingWeight: 800,
      headingScale: 1.6,
    },
    spacing: { pagePaddingY: 56, blockGap: 14 },
    buttons: { variant: "filled", shape: "pill", height: 52 },
    googleFonts: ["Sora"],
  },
  {
    id: "stripe-gradient",
    name: "Stripe",
    description: "Signature gradient hero, meticulous grid.",
    category: "startup",
    tier: "premium",
    layoutId: "stripe",
    preset: "modern",
    style: "gradient",
    tags: ["stripe", "gradient"],
    popularity: 94,
    flags: { isTrending: true },
    colors: {
      background: "linear-gradient(135deg,#a5f3fc 0%,#c4b5fd 45%,#f0abfc 100%)",
      backgroundSolid: "#c4b5fd",
      primary: "#635bff",
      accent: "#0a2540",
      text: "#0a2540",
    },
    typography: {
      fontFamily: '"Inter", sans-serif',
      headingFamily: '"Inter", sans-serif',
      headingWeight: 800,
    },
    buttons: { variant: "gradient", shape: "rounded", radius: 12, height: 48 },
  },
  {
    id: "linear-dark",
    name: "Linear",
    description: "Precise dark UI with hairline borders.",
    category: "startup",
    tier: "premium",
    layoutId: "linear",
    preset: "modern",
    style: "dark",
    tags: ["linear", "dark"],
    popularity: 91,
    flags: { isFeatured: true },
    colors: {
      background: "#08090a",
      backgroundSolid: "#08090a",
      surface: "#0e1013",
      card: "#0e1013",
      text: "#f7f8f8",
      textMuted: "#8a8f98",
      border: "#23252a",
      primary: "#5e6ad2",
      primaryText: "#ffffff",
      secondary: "#1c1d21",
      accent: "#a8b1ff",
    },
    typography: { headingWeight: 600, letterSpacing: -0.01 },
    buttons: { variant: "filled", shape: "rounded", radius: 8, height: 40 },
  },
  {
    id: "framer-playful",
    name: "Framer",
    description: "Playful blocks, bright color, motion-first.",
    category: "designer",
    tier: "premium",
    layoutId: "framer",
    preset: "creator",
    style: "gradient",
    tags: ["framer", "motion"],
    popularity: 88,
    colors: {
      background: "linear-gradient(135deg,#0055ff 0%,#00ccff 100%)",
      backgroundSolid: "#0055ff",
      primary: "#ffffff",
      primaryText: "#0055ff",
      accent: "#ffd60a",
      text: "#ffffff",
    },
    typography: { headingWeight: 900, headingScale: 1.4 },
    buttons: { variant: "filled", shape: "rounded", radius: 20, height: 56 },
  },
  {
    id: "notion-pro",
    name: "Notion Pro",
    description: "Editorial page with premium serif type.",
    category: "writer",
    tier: "premium",
    layoutId: "notion",
    preset: "minimal",
    style: "light",
    tags: ["notion", "editorial"],
    popularity: 79,
    colors: { background: "#faf9f7", backgroundSolid: "#faf9f7", text: "#191919", textMuted: "#6f6e69" },
    typography: {
      fontFamily: '"Cormorant Garamond", Georgia, serif',
      headingFamily: '"Cormorant Garamond", Georgia, serif',
      headingWeight: 500,
      baseSize: 16,
    },
    googleFonts: ["Cormorant Garamond"],
  },

  // ── Luxury / Black ────────────────────────────────────────────────
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    description: "Deep black with gold serif accents.",
    category: "luxury",
    tier: "premium",
    layoutId: "luxury",
    preset: "luxury",
    style: "dark",
    tags: ["premium", "gold"],
    popularity: 89,
    flags: { isFeatured: true },
  },
  {
    id: "black-premium",
    name: "Black Premium",
    description: "Pure black, monochrome minimalism.",
    category: "luxury",
    tier: "premium",
    layoutId: "editorial",
    preset: "luxury",
    style: "dark",
    tags: ["black", "mono"],
    popularity: 84,
    colors: {
      background: "#000000",
      backgroundSolid: "#000000",
      surface: "#0a0a0a",
      card: "#0a0a0a",
      text: "#f5f5f5",
      textMuted: "#a3a3a3",
      border: "#1f1f1f",
      primary: "#ffffff",
      primaryText: "#000000",
      accent: "#ffffff",
    },
    typography: {
      fontFamily: '"Sora", sans-serif',
      headingFamily: '"Sora", sans-serif',
      headingWeight: 400,
      letterSpacing: 0.1,
      textTransform: "uppercase",
    },
    buttons: { variant: "outline", shape: "square", radius: 0, height: 52 },
    googleFonts: ["Sora"],
  },

  // ── Neon / Gaming / AI ────────────────────────────────────────────
  {
    id: "neon-cyber",
    name: "Neon Cyber",
    description: "Cyberpunk pinks and cyans with glow.",
    category: "neon",
    tier: "premium",
    layoutId: "neon-cyber",
    preset: "neon",
    style: "neon",
    tags: ["cyber", "glow"],
    popularity: 90,
    flags: { isTrending: true },
  },
  {
    id: "gaming-arena",
    name: "Gaming Arena",
    description: "Hard-edged gamer vibe with electric accents.",
    category: "gaming",
    tier: "premium",
    layoutId: "gaming",
    preset: "neon",
    style: "neon",
    tags: ["gaming", "esports"],
    popularity: 82,
    colors: {
      background: "linear-gradient(135deg,#0a0a0a 0%,#1a0033 100%)",
      backgroundSolid: "#0a0a0a",
      primary: "#a3ff00",
      primaryText: "#0a0a0a",
      accent: "#ff006e",
      text: "#f5f5f5",
    },
    typography: {
      fontFamily: '"Space Grotesk", sans-serif',
      headingFamily: '"Space Grotesk", sans-serif',
      headingWeight: 800,
      textTransform: "uppercase",
    },
    buttons: { variant: "filled", shape: "square", radius: 2, height: 50 },
    googleFonts: ["Space Grotesk"],
  },
  {
    id: "ai-neural",
    name: "AI Neural",
    description: "Machine-learning dark with iridescent gradient.",
    category: "ai",
    tier: "premium",
    layoutId: "linear",
    preset: "modern",
    style: "dark",
    tags: ["ai", "future"],
    popularity: 87,
    flags: { isNew: true, isTrending: true },
    colors: {
      background: "radial-gradient(circle at 20% 0%,#1e1b4b 0%,#020617 60%)",
      backgroundSolid: "#020617",
      surface: "#0f172a",
      card: "#0f172a",
      text: "#f8fafc",
      textMuted: "#94a3b8",
      border: "#1e293b",
      primary: "#818cf8",
      accent: "#22d3ee",
    },
    typography: {
      fontFamily: '"Space Grotesk", sans-serif',
      headingFamily: '"Space Grotesk", sans-serif',
      headingWeight: 700,
    },
    buttons: { variant: "gradient", shape: "pill", height: 46 },
    googleFonts: ["Space Grotesk"],
  },

  // ── Music ─────────────────────────────────────────────────────────
  {
    id: "music-artist",
    name: "Music Artist",
    description: "Concert-poster dark for musicians.",
    category: "musician",
    tier: "premium",
    layoutId: "neon-cyber",
    preset: "neon",
    style: "dark",
    tags: ["music", "artist"],
    popularity: 80,
    colors: { primary: "#f97316", accent: "#eab308" },
  },
  {
    id: "music-vinyl",
    name: "Vinyl",
    description: "Moody stage lights for musicians.",
    category: "musician",
    tier: "premium",
    layoutId: "editorial",
    preset: "luxury",
    style: "dark",
    tags: ["music", "vinyl"],
    popularity: 72,
  },

  // ── Fashion ───────────────────────────────────────────────────────
  {
    id: "fashion-runway",
    name: "Runway",
    description: "High-fashion editorial spread.",
    category: "fashion",
    tier: "premium",
    layoutId: "magazine",
    preset: "luxury",
    style: "dark",
    tags: ["fashion", "runway"],
    popularity: 86,
    flags: { isTrending: true },
  },
  {
    id: "fashion-boutique",
    name: "Boutique",
    description: "Elegant serif on cream for fashion.",
    category: "fashion",
    tier: "premium",
    layoutId: "editorial",
    preset: "luxury",
    style: "light",
    tags: ["fashion", "boutique"],
    popularity: 75,
    colors: {
      background: "#f6f1eb",
      backgroundSolid: "#f6f1eb",
      surface: "#efe7dd",
      card: "#ffffff",
      text: "#2b1e12",
      textMuted: "#7a6a58",
      primary: "#8b4513",
      accent: "#c9a24c",
    },
    typography: {
      fontFamily: '"Cormorant Garamond", Georgia, serif',
      headingFamily: '"Cormorant Garamond", Georgia, serif',
      headingWeight: 500,
    },
    googleFonts: ["Cormorant Garamond"],
  },

  // ── Photographer ──────────────────────────────────────────────────
  {
    id: "photographer-gallery",
    name: "Gallery",
    description: "Museum wall for photographers.",
    category: "photographer",
    tier: "premium",
    layoutId: "portfolio",
    preset: "minimal",
    style: "dark",
    tags: ["photo", "gallery"],
    popularity: 77,
    colors: { background: "#0a0a0a", backgroundSolid: "#0a0a0a", text: "#f5f5f5", textMuted: "#a3a3a3", primary: "#ffffff", primaryText: "#000000", card: "#141414", border: "#1f1f1f" },
  },
  {
    id: "photographer-mono",
    name: "Monochrome",
    description: "Silver-print aesthetic.",
    category: "photographer",
    tier: "premium",
    layoutId: "editorial",
    preset: "minimal",
    style: "light",
    tags: ["photo", "mono"],
    popularity: 68,
  },

  // ── Restaurant / Cafe ─────────────────────────────────────────────
  {
    id: "restaurant-editorial",
    name: "Trattoria",
    description: "Menu-style editorial for restaurants.",
    category: "restaurant",
    tier: "premium",
    layoutId: "editorial",
    preset: "luxury",
    style: "dark",
    tags: ["menu", "food"],
    popularity: 74,
  },
  {
    id: "restaurant-menu",
    name: "Bistro",
    description: "Warm ivory menu magazine.",
    category: "restaurant",
    tier: "premium",
    layoutId: "magazine",
    preset: "luxury",
    style: "light",
    tags: ["menu", "bistro"],
    popularity: 65,
    colors: {
      background: "#fbf6ee",
      backgroundSolid: "#fbf6ee",
      surface: "#f2e9d8",
      card: "#ffffff",
      text: "#2b1e12",
      textMuted: "#6b5b3f",
      primary: "#8b0000",
      accent: "#c9a24c",
    },
    typography: {
      fontFamily: '"Playfair Display", Georgia, serif',
      headingFamily: '"Playfair Display", Georgia, serif',
      headingWeight: 700,
    },
    googleFonts: ["Playfair Display"],
  },
  {
    id: "cafe-roastery",
    name: "Roastery",
    description: "Cozy espresso browns.",
    category: "cafe",
    tier: "premium",
    layoutId: "editorial",
    preset: "creator",
    style: "gradient",
    tags: ["coffee"],
    popularity: 62,
    colors: {
      background: "linear-gradient(180deg,#efe4d5 0%,#d2b48c 100%)",
      backgroundSolid: "#d2b48c",
      primary: "#3e2723",
      accent: "#8d6e63",
    },
  },
  {
    id: "cafe-artisan",
    name: "Artisan",
    description: "Handcrafted magazine cafe layout.",
    category: "cafe",
    tier: "premium",
    layoutId: "magazine",
    preset: "minimal",
    style: "light",
    tags: ["coffee", "artisan"],
    popularity: 55,
  },

  // ── Fitness ───────────────────────────────────────────────────────
  {
    id: "gym-iron",
    name: "Iron",
    description: "Bold split hero for personal trainers.",
    category: "fitness",
    tier: "premium",
    layoutId: "split-hero",
    preset: "modern",
    style: "light",
    tags: ["gym", "trainer"],
    popularity: 76,
    colors: { primary: "#dc2626", accent: "#111827" },
    typography: { headingWeight: 900, textTransform: "uppercase" },
  },
  {
    id: "gym-athletic",
    name: "Athletic",
    description: "Stadium-lights dark for athletes.",
    category: "fitness",
    tier: "premium",
    layoutId: "gaming",
    preset: "neon",
    style: "dark",
    tags: ["athlete", "sport"],
    popularity: 69,
    colors: {
      background: "linear-gradient(135deg,#0a0a0a 0%,#7f1d1d 100%)",
      backgroundSolid: "#0a0a0a",
      primary: "#facc15",
      accent: "#ef4444",
    },
  },

  // ── Real estate ───────────────────────────────────────────────────
  {
    id: "realestate-luxury",
    name: "Estate Luxe",
    description: "Split hero for luxury property listings.",
    category: "realestate",
    tier: "premium",
    layoutId: "split-hero",
    preset: "luxury",
    style: "dark",
    tags: ["real estate", "luxury"],
    popularity: 71,
  },

  // ── Doctor ────────────────────────────────────────────────────────
  {
    id: "doctor-clinic",
    name: "Clinic",
    description: "Calming clinic corporate layout.",
    category: "doctor",
    tier: "premium",
    layoutId: "corporate",
    preset: "business",
    style: "light",
    tags: ["doctor", "clinic"],
    popularity: 64,
    colors: { primary: "#0ea5e9", accent: "#22c55e" },
  },
  {
    id: "doctor-medical",
    name: "Medical",
    description: "Precise medical grid.",
    category: "doctor",
    tier: "premium",
    layoutId: "linear",
    preset: "minimal",
    style: "light",
    tags: ["medical"],
    popularity: 58,
    colors: { primary: "#0891b2", accent: "#059669" },
  },

  // ── Wedding ───────────────────────────────────────────────────────
  {
    id: "wedding-elegant",
    name: "Vows",
    description: "Elegant serif wedding invite.",
    category: "wedding",
    tier: "premium",
    layoutId: "editorial",
    preset: "luxury",
    style: "light",
    tags: ["wedding", "elegant"],
    popularity: 73,
    colors: {
      background: "#faf5ef",
      backgroundSolid: "#faf5ef",
      surface: "#f0e6d8",
      card: "#ffffff",
      text: "#3a2c1a",
      textMuted: "#7b6a4e",
      primary: "#b45309",
      accent: "#d97706",
    },
    typography: {
      fontFamily: '"Cormorant Garamond", Georgia, serif',
      headingFamily: '"Cormorant Garamond", Georgia, serif',
      headingWeight: 400,
    },
    googleFonts: ["Cormorant Garamond"],
  },
  {
    id: "wedding-blossom",
    name: "Blossom",
    description: "Blush glass wedding hub.",
    category: "wedding",
    tier: "premium",
    layoutId: "glass",
    preset: "glass",
    style: "glass",
    tags: ["wedding", "blush"],
    popularity: 66,
    colors: {
      background: "linear-gradient(135deg,#fecdd3 0%,#f9a8d4 100%)",
      backgroundSolid: "#fecdd3",
      primary: "#be185d",
      accent: "#db2777",
    },
  },

  // ── Personal brand ────────────────────────────────────────────────
  {
    id: "personal-brand",
    name: "Personal Brand",
    description: "Apple-like hero for personal brands.",
    category: "personal",
    tier: "premium",
    layoutId: "apple",
    preset: "modern",
    style: "light",
    tags: ["personal"],
    popularity: 81,
    flags: { isNew: true },
  },

  // ── Corporate / Agency / Startup ──────────────────────────────────
  {
    id: "corporate-suite",
    name: "Corporate Suite",
    description: "Enterprise-grade corporate composition.",
    category: "corporate",
    tier: "premium",
    layoutId: "corporate",
    preset: "business",
    style: "light",
    tags: ["corporate", "enterprise"],
    popularity: 63,
    colors: { primary: "#0f172a", accent: "#0284c7" },
  },
  {
    id: "agency-studio",
    name: "Studio",
    description: "Bold split hero for agencies.",
    category: "agency",
    tier: "premium",
    layoutId: "split-hero",
    preset: "modern",
    style: "light",
    tags: ["agency"],
    popularity: 70,
  },
  {
    id: "startup-launch",
    name: "Launch",
    description: "Stripe-style startup landing.",
    category: "startup",
    tier: "premium",
    layoutId: "stripe",
    preset: "modern",
    style: "gradient",
    tags: ["startup"],
    popularity: 78,
  },
  {
    id: "ecom-storefront",
    name: "Storefront",
    description: "Bento product grid for shops.",
    category: "ecommerce",
    tier: "premium",
    layoutId: "bento",
    preset: "modern",
    style: "light",
    tags: ["shop", "storefront"],
    popularity: 74,
    flags: { isNew: true },
  },

  // ── Minimal / Dark / Neumorph ─────────────────────────────────────
  {
    id: "minimal-white",
    name: "Minimal White",
    description: "Pure white with massive typography.",
    category: "minimal",
    tier: "premium",
    layoutId: "apple",
    preset: "minimal",
    style: "light",
    tags: ["minimal"],
    popularity: 85,
    typography: { headingWeight: 900, headingScale: 1.8, letterSpacing: -0.02 },
  },
  {
    id: "dark-elegant",
    name: "Dark Elegant",
    description: "Deep charcoal editorial for premium brands.",
    category: "luxury",
    tier: "premium",
    layoutId: "editorial",
    preset: "luxury",
    style: "dark",
    tags: ["dark", "elegant"],
    popularity: 76,
    colors: { background: "#0f0f10", backgroundSolid: "#0f0f10", primary: "#e5e5e5", accent: "#d4af37" },
  },
  {
    id: "neumorph-soft",
    name: "Neumorph",
    description: "Soft inset neumorphic surfaces.",
    category: "modern",
    tier: "premium",
    layoutId: "neumorph",
    preset: "minimal",
    style: "light",
    tags: ["neumorphism", "soft"],
    popularity: 67,
    colors: { background: "#e0e5ec", backgroundSolid: "#e0e5ec", card: "#e0e5ec", surface: "#e0e5ec", primary: "#4361ee", accent: "#4cc9f0" },
    card: { background: "#e0e5ec", radius: 20, border: "0", shadow: "9px 9px 18px #b8bcc2, -9px -9px 18px #ffffff" },
    buttons: { variant: "soft", shape: "rounded", radius: 16, height: 48, shadow: "6px 6px 12px #b8bcc2, -6px -6px 12px #ffffff" },
  },

  // ── Glass variants ────────────────────────────────────────────────
  {
    id: "glass-frost",
    name: "Frost",
    description: "Crisp frosted glass on ice palette.",
    category: "glass",
    tier: "premium",
    layoutId: "glass",
    preset: "glass",
    style: "glass",
    tags: ["glass", "frost"],
    popularity: 69,
  },
  {
    id: "glass-aurora",
    name: "Aurora Glass",
    description: "Aurora borealis glass gradient.",
    category: "glass",
    tier: "premium",
    layoutId: "glass",
    preset: "glass",
    style: "glass",
    tags: ["glass", "aurora"],
    popularity: 72,
    flags: { isNew: true },
    colors: {
      background: "linear-gradient(135deg,#00ff88 0%,#00ccff 50%,#8b5cf6 100%)",
      backgroundSolid: "#8b5cf6",
      primary: "#0f172a",
      accent: "#7c3aed",
    },
  },

  // ── Creator / Influencer ──────────────────────────────────────────
  {
    id: "creator-tiktok",
    name: "TikTok Creator",
    description: "Vertical story card for short-form creators.",
    category: "creator",
    tier: "premium",
    layoutId: "story-card",
    preset: "creator",
    style: "gradient",
    tags: ["tiktok", "creator"],
    popularity: 83,
    flags: { isTrending: true },
    colors: {
      background: "linear-gradient(135deg,#000000 0%,#25f4ee 50%,#fe2c55 100%)",
      backgroundSolid: "#000000",
      primary: "#fe2c55",
      accent: "#25f4ee",
      text: "#ffffff",
    },
  },
  {
    id: "influencer-fame",
    name: "Fame",
    description: "Loud gradient story card for influencers.",
    category: "influencer",
    tier: "premium",
    layoutId: "story-card",
    preset: "creator",
    style: "gradient",
    tags: ["influencer"],
    popularity: 79,
    colors: {
      background: "linear-gradient(135deg,#ff006e 0%,#8338ec 50%,#3a86ff 100%)",
      backgroundSolid: "#8338ec",
      primary: "#ffffff",
      primaryText: "#8338ec",
      accent: "#ffbe0b",
    },
  },

  // ── Podcaster / Writer / Designer / Developer ─────────────────────
  {
    id: "podcaster-pro",
    name: "Podcast Pro",
    description: "Studio dark for podcasters.",
    category: "podcaster",
    tier: "premium",
    layoutId: "editorial",
    preset: "luxury",
    style: "dark",
    tags: ["podcast"],
    popularity: 68,
    colors: { primary: "#a855f7", accent: "#ec4899" },
  },
  {
    id: "writer-quill",
    name: "Quill",
    description: "Editorial serif for authors.",
    category: "writer",
    tier: "premium",
    layoutId: "editorial",
    preset: "luxury",
    style: "dark",
    tags: ["writing"],
    popularity: 61,
  },
  {
    id: "designer-canvas",
    name: "Canvas",
    description: "Bento gallery for designers.",
    category: "designer",
    tier: "premium",
    layoutId: "bento",
    preset: "glass",
    style: "glass",
    tags: ["design"],
    popularity: 73,
  },
  {
    id: "developer-terminal",
    name: "Dev Terminal",
    description: "Neon terminal for developers.",
    category: "developer",
    tier: "premium",
    layoutId: "terminal",
    preset: "neon",
    style: "neon",
    tags: ["dev", "terminal"],
    popularity: 77,
    flags: { isTrending: true },
    colors: {
      background: "#0d0208",
      backgroundSolid: "#0d0208",
      primary: "#00ff41",
      primaryText: "#0d0208",
      accent: "#00ff41",
      text: "#00ff41",
      card: "#0d0208",
      border: "#003b00",
    },
    typography: {
      fontFamily: '"JetBrains Mono", monospace',
      headingFamily: '"JetBrains Mono", monospace',
      buttonFamily: '"JetBrains Mono", monospace',
    },
    buttons: { variant: "outline", shape: "square", radius: 0, height: 40 },
    googleFonts: ["JetBrains Mono"],
  },
  {
    id: "developer-code",
    name: "Code Editor",
    description: "Editor-inspired dark for engineers.",
    category: "developer",
    tier: "premium",
    layoutId: "linear",
    preset: "modern",
    style: "dark",
    tags: ["dev", "code"],
    popularity: 70,
    colors: {
      background: "#1e1e2e",
      backgroundSolid: "#1e1e2e",
      surface: "#181825",
      card: "#181825",
      text: "#cdd6f4",
      textMuted: "#a6adc8",
      border: "#313244",
      primary: "#89b4fa",
      accent: "#f5c2e7",
    },
    typography: {
      fontFamily: '"JetBrains Mono", monospace',
      headingFamily: '"JetBrains Mono", monospace',
    },
    googleFonts: ["JetBrains Mono"],
  },

  // ── Beauty ────────────────────────────────────────────────────────
  {
    id: "beauty-aura",
    name: "Aura",
    description: "Soft glass palette for beauty brands.",
    category: "beauty",
    tier: "premium",
    layoutId: "glass",
    preset: "glass",
    style: "glass",
    tags: ["beauty"],
    popularity: 65,
  },
  {
    id: "beauty-rose",
    name: "Rose Petal",
    description: "Serif editorial for beauty labels.",
    category: "beauty",
    tier: "premium",
    layoutId: "editorial",
    preset: "luxury",
    style: "light",
    tags: ["beauty", "rose"],
    popularity: 60,
    colors: {
      background: "#fef2f2",
      backgroundSolid: "#fef2f2",
      surface: "#fee2e2",
      card: "#ffffff",
      text: "#4c0519",
      textMuted: "#9f1239",
      primary: "#e11d48",
      accent: "#f43f5e",
    },
    typography: {
      fontFamily: '"Cormorant Garamond", Georgia, serif',
      headingFamily: '"Cormorant Garamond", Georgia, serif',
    },
    googleFonts: ["Cormorant Garamond"],
  },

  // ── Event / Travel / Education / Nonprofit ────────────────────────
  {
    id: "event-encore",
    name: "Encore",
    description: "Neon event poster for concerts and clubs.",
    category: "event",
    tier: "premium",
    layoutId: "gaming",
    preset: "neon",
    style: "neon",
    tags: ["event", "party"],
    popularity: 62,
  },
  {
    id: "travel-wanderlust",
    name: "Wanderlust",
    description: "Magazine feature for travel creators.",
    category: "travel",
    tier: "premium",
    layoutId: "magazine",
    preset: "creator",
    style: "gradient",
    tags: ["travel", "magazine"],
    popularity: 71,
    colors: {
      background: "linear-gradient(180deg,#fef3c7 0%,#fed7aa 100%)",
      backgroundSolid: "#fed7aa",
      primary: "#c2410c",
      accent: "#f97316",
    },
  },
  {
    id: "education-scholar",
    name: "Scholar",
    description: "Notion-style page for educators.",
    category: "education",
    tier: "premium",
    layoutId: "notion",
    preset: "minimal",
    style: "light",
    tags: ["education", "scholar"],
    popularity: 54,
  },
  {
    id: "nonprofit-cause",
    name: "Impact",
    description: "Split hero for nonprofits.",
    category: "nonprofit",
    tier: "premium",
    layoutId: "split-hero",
    preset: "business",
    style: "light",
    tags: ["nonprofit", "impact"],
    popularity: 51,
    colors: { primary: "#059669", accent: "#0284c7" },
  },

  // ── More premium picks to reach 50 ────────────────────────────────
  {
    id: "consultant-advisor",
    name: "Advisor",
    description: "Executive briefing look for consultants.",
    category: "consultant",
    tier: "premium",
    layoutId: "corporate",
    preset: "business",
    style: "light",
    tags: ["consulting"],
    popularity: 59,
  },
  {
    id: "personal-noir",
    name: "Noir",
    description: "Pure black personal statement.",
    category: "personal",
    tier: "premium",
    layoutId: "apple",
    preset: "luxury",
    style: "dark",
    tags: ["personal", "noir"],
    popularity: 72,
    colors: { background: "#000", backgroundSolid: "#000", primary: "#fff", primaryText: "#000", accent: "#fff" },
  },
  {
    id: "creator-neon",
    name: "Neon Creator",
    description: "Story card with neon accents.",
    category: "creator",
    tier: "premium",
    layoutId: "story-card",
    preset: "neon",
    style: "neon",
    tags: ["creator", "neon"],
    popularity: 66,
  },
  {
    id: "modern-mint",
    name: "Mint Modern",
    description: "Modern mint accents on soft white.",
    category: "modern",
    tier: "premium",
    layoutId: "framer",
    preset: "modern",
    style: "light",
    tags: ["mint", "modern"],
    popularity: 58,
    colors: { primary: "#059669", accent: "#14b8a6" },
  },

  // ── Enterprise (Shikhar only) ─────────────────────────────────────
  {
    id: "enterprise-onyx",
    name: "Onyx Enterprise",
    description: "Onyx black with platinum accents.",
    category: "corporate",
    tier: "enterprise",
    layoutId: "corporate",
    preset: "luxury",
    style: "dark",
    tags: ["enterprise", "white-label"],
    popularity: 88,
    flags: { isFeatured: true, isNew: true },
    colors: {
      background: "#0b0b0d",
      backgroundSolid: "#0b0b0d",
      surface: "#111114",
      card: "#141419",
      primary: "#e5e7eb",
      primaryText: "#0b0b0d",
      accent: "#cbd5e1",
      text: "#f1f5f9",
    },
  },
  {
    id: "enterprise-platinum",
    name: "Platinum Suite",
    description: "White-label platinum for global brands.",
    category: "corporate",
    tier: "enterprise",
    layoutId: "editorial",
    preset: "luxury",
    style: "light",
    tags: ["enterprise", "platinum"],
    popularity: 82,
    flags: { isFeatured: true },
    colors: {
      background: "#f8fafc",
      backgroundSolid: "#f8fafc",
      surface: "#f1f5f9",
      card: "#ffffff",
      primary: "#0f172a",
      accent: "#64748b",
    },
  },
  {
    id: "enterprise-fortune",
    name: "Fortune",
    description: "Executive layout for Fortune-500 brands.",
    category: "corporate",
    tier: "enterprise",
    layoutId: "split-hero",
    preset: "business",
    style: "light",
    tags: ["enterprise", "fortune"],
    popularity: 79,
  },
  {
    id: "enterprise-agency",
    name: "Agency Suite Pro",
    description: "Multi-brand agency showcase.",
    category: "agency",
    tier: "enterprise",
    layoutId: "bento",
    preset: "modern",
    style: "light",
    tags: ["enterprise", "agency"],
    popularity: 76,
  },
  {
    id: "enterprise-luxury-black",
    name: "Obsidian",
    description: "Ultra-luxury obsidian black.",
    category: "luxury",
    tier: "enterprise",
    layoutId: "luxury",
    preset: "luxury",
    style: "dark",
    tags: ["enterprise", "obsidian"],
    popularity: 85,
    colors: { background: "#000", backgroundSolid: "#000", primary: "#d4af37", accent: "#c9a24c" },
  },
];
